
name: envoi du mail


on:
    schedule: 
    -  cron: '15 * * * *'
jobs:
  envoi_mail:
    permissions:
       contents: write
       pages : write
    runs-on: ubuntu-latest
    
    
    steps:
        uses: actions/checkout@v4
        
      - name: Upload a build Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: rapport.pdf
          path: rapport.pdf

      - name: Envoi du mail
    
      with:
    
          server_port: 465
          secure: true
          username: ${{secrets.MAIL_USERNAME_GMA}}
          password: ${{secrets.MAIL_PASSWORD_GMA}}
          subject: Le tableau recapitulatif du jour
          to: dataimpactafrica@gmail.com
          from:  Christian Cyriaque 
          body: Veuillez trouver ci-joint le tableau recapitulatif de la situation de la collecte de données
          ignore_cert: true
          convert_markdown: true
          attachments: rapport.pdf
          priority: low
   