on:
     schedule:
       - cron: '*/8 * * * *'
      
jobs:
    envoi_mail:
      permissions:
        contents: write
        pages: write
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v4
        
        - name: Upload a Build Artifact
          uses: actions/upload-artifact@v4.1.0
          with:
            name: rapport.html
            path: rapport.html

        - name: Envoi de mail
          uses: dawidd6/action-send-mail@v3
          with:
            server_address: smtp.gmail.com
            server_port: 465
            secure: true
            username: ${{secrets.MAIL_USERNAME_GHA}}
            password: ${{secrets.MAIL_PASSWORD_GHA}}
            subject: Le Tableau recapitulatif du jour
            to: ouedraogocyriaque1@gmail.com
            from: Cyriaque Ouedraogo
            body: Veuillez trouver ci-joint le tableau recapitulatif de la situation de la collecte de ce jour
            cc: dataimpact@gmail.com
            ignore_cert: true
            convert_markdown: true
            attachments: rapport.html
            priority: low
