name: Data Import, Export, and Email

on:
  schedule:
    - cron: "/5 * * *"


jobs:
  import-data:
    permissions:
      contents: write
      pages: write
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        
      - name: Install R
        uses: r-lib/actions/setup-r@v2

      - name: Install packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::tidyverse
            any::robotoolbox
            any::janitor

      - name: Import data
        run: Rscript -e 'source("import_data.R")'
        env:
          MY_TOKEN: ${{secrets.MY_TOKEN_GHA}}
          MY_UID: ${{secrets.MY_UID_GHA}}
          MY_USER: ${{secrets.MY_USER_GHA}}
          MY_PASSWORD: ${{secrets.MY_PASSWORD}}

      - name: Commit results
        run: |
          git config --local user.email "ouedraogocyriaque1@gmail.com"
          git config --local user.name "ChristianCyriaque"
          git add mydf.rds
          git commit -m 'Data updated' || echo "No changes to commit"
          git push origin || echo "No changes to commit"

  generate-pdf:
    permissions:
      contents: write
      pages: write
    runs-on: ubuntu-latest
    needs: import-data  # Attendre la fin de l'import avant de générer le rapport
    steps:
      - uses: actions/checkout@v4

      - name: Install R
        uses: r-lib/actions/setup-r@v2

      - name: Install packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::knitr
            any::rmarkdown
            any::downlit
            any::xml2
            any::gt
            any::tidyverse

      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          tinytex: true

      - name: Render Quarto Project to PDF
        uses: quarto-dev/quarto-actions/render@v2
        with:
          to: pdf
          path: rapport.Rmd

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.1.0
        with:
          name: rapport.pdf
          path: rapport.pdf

      - name: Commit results
        run: |
          git config --local user.email "ouedraogocyriaque1@gmail.com"
          git config --local user.name "ChristianCyriaque"
          git add rapport.pdf
          git commit -m 'Rapport updated' || echo "No changes to commit"
          git push origin || echo "No changes to commit"

  envoi-mail:
    permissions:
      contents: write
      pages: write
    runs-on: ubuntu-latest
    needs: generate-pdf  # Attendre la fin de la génération du rapport avant d'envoyer l'email
    steps:
      - uses: actions/checkout@v4
      
      - name: Download Artifact
        uses: actions/download-artifact@v4.1.0
        with:
          name: rapport.pdf

      - name: Envoi de mail
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{secrets.MAIL_USERNAME_GHA}}
          password: ${{secrets.MAIL_PASSWORD_GHA}}
          subject: Le Tableau récapitulatif du jour
          to: ouedraogocyriaque1@gmail.com
          from: Cyriaque Ouedraogo
          body: Veuillez trouver ci-joint le tableau récapitulatif de la situation de la collecte de ce jour
          cc: ollofabrice5@gmail.com
          ignore_cert: true
          convert_markdown: true
          attachments: rapport.pdf
          priority: low
