# This is a basic workflow that is manually triggered

name: Importation_données

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    




jobs:
  import_data:
    permissions:
       contents: write
       pages : write
    runs-on: ubuntu-latest
    
    
    steps:
    
      - name: Check out repository
        uses: actions/checkout@v3
        
      - name: install R
        uses: r-lib/actions/setup-r@v2

      - name: Install packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::tidyverse 
            any::robotoolbox

      

      - name: Importation des données
        run: Rscript -e 'source("import_data.Rmd")'
        env:
          MY_TOKEN: ${{secrets.MY_TOKEN_GMA}}
          MY_IUD: ${{secrets.MY_IUD_GMA}}

      - name: Commit results
        run: |
          git config --local user.email "ouedraogocyriaque1@gmail.com"
          git config --local user.name "OUEDRACHRISTIAN"
          git add mydf.rds
          git commit -m 'Data updated' || echo "No changes to commit"
          git push origin || echo "No changes to commit"